FROM golang:alpine AS builder

WORKDIR /build

ADD go.mod .

COPY . .

RUN go build -o ./mailganer ./cmd/main.go

FROM alpine

WORKDIR /build

COPY --from=builder /build/mailganer /build/mailganer
COPY --from=builder /build/.env .
COPY --from=builder /build/templates /build/templates


CMD ["./mailganer"]

